//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickQuant.Model.IntellectualOrder {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class IntellectualOrdersLib : global::System.Configuration.ApplicationSettingsBase {
        
        private static IntellectualOrdersLib defaultInstance = ((IntellectualOrdersLib)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new IntellectualOrdersLib())));
        
        public static IntellectualOrdersLib Default {
            get {
                return defaultInstance;
            }
        }
    }
}
