namespace TickQuant.Common
{
    public enum EIndicatorType
    {
        SMA=0,
        EMA,
        MACD,
        BOLLBAND,
        RSI,
        SAR,
        ADX,
        AROON,
        ATR,
        ADXR,
        AROONOSC,
        CCI,
        SR,
        DMI,
        DYMOI,
        EMAOSC,
        ER,
        FASTSTO,
        FASTSTOOSC,
        FULLSTO,
        HIGHCLOSE,
        HIGHHIGH,
        HISTHIGHCLOSE,
        HISTLOWLOW,
        HISTLOWCLOSE,
        HMA,
        ICHIMOKU,
        KAMA,       
    }
}
